server:
  port: 8083

spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    defer-datasource-initialization: true
  datasource:
#    username: wvoort66
#    password: wvoort66
#    url: jdbc:postgresql://localhost:5432/keycloak
#    hikari:
#      maximum-pool-size: 25
#      minimum-idle: 1
#    driver-class-name: org.postgresql.Driver
    username: sa
    url: jdbc:h2:mem:customdb;DB_CLOSE_ON_EXIT=FALSE


keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: wvoort66-admin
      password: passme
    realmImportFile: wc2022-realm.json

